FROM node:latest
WORKDIR /docker
COPY ./javascript-app ./
RUN apt-get update -y
RUN apt-get install nginx -y
RUN npm install
RUN npm run ng build -- --output-path=/var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
